FROM freqtradeorg/freqtrade:stable

# Switch user to root if you must install something from apt
# Don't forget to switch the user back below!
# USER root

# Install Pillow for image generation (/pnl command)
RUN pip install --user --no-cache-dir Pillow==10.4.0

# Switch back to user (only if you required root above)
# USER ftuser
